import { boolean, date, decimal, integer, jsonb, pgEnum, pgTable, serial, text, timestamp, varchar } from "drizzle-orm/pg-core";

export const userRoleEnum = pgEnum("user_role", ["user", "admin"]);
export const users = pgTable("users", {
  id: serial("id").primaryKey(), openId: varchar("openId", { length: 320 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), passwordHash: text("passwordHash"), loginMethod: varchar("loginMethod", { length: 64 }), role: userRoleEnum("role").default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

const businessRoles = ["admin", "sales", "tailor", "inventory", "payroll"] as const;
export type BusinessRole = (typeof businessRoles)[number];
export const businessRoleEnum = pgEnum("business_role", businessRoles);
export const accessRequestStatusEnum = pgEnum("access_request_status", ["pending", "approved", "rejected"]);
export const tailoringOrderStatusEnum = pgEnum("tailoring_order_status", ["draft", "confirmed", "cutting", "stitching", "fitting", "ready", "handed_over", "cancelled"]);
export const inventoryCategoryEnum = pgEnum("inventory_category", ["fabric", "lining", "buttons", "thread", "accessory", "other"]);
export const inventoryItemTypeEnum = pgEnum("inventory_item_type", ["material", "item"]);
export const stockMovementTypeEnum = pgEnum("stock_movement_type", ["opening", "adjustment", "sale", "return", "purchase"]);
export const serviceCategoryEnum = pgEnum("service_category", ["tailoring", "fabric", "alteration", "accessory", "other"]);
export const paymentMethodEnum = pgEnum("payment_method", ["cash", "benefitpay", "bank_transfer", "credit_card"]);
export const paymentStatusEnum = pgEnum("payment_status", ["paid", "partial", "unpaid"]);
export const invoiceDeliveryChannelEnum = pgEnum("invoice_delivery_channel", ["email", "whatsapp", "share"]);
export const invoiceDeliveryStatusEnum = pgEnum("invoice_delivery_status", ["prepared", "sent", "failed"]);
export const saleSourceEnum = pgEnum("sale_source", ["counter", "manual", "tailoring"]);
export const posSessionStatusEnum = pgEnum("pos_session_status", ["open", "closed"]);
export const posOrderStatusEnum = pgEnum("pos_order_status", ["held", "open", "paid", "cancelled", "refunded"]);
export const discountTypeEnum = pgEnum("discount_type", ["percent", "amount"]);
export const invoiceStatusEnum = pgEnum("invoice_status", ["paid", "partial", "unpaid", "void"]);
export const attendanceStatusEnum = pgEnum("attendance_status", ["present", "absent", "leave", "half_day"]);

export const userBusinessRoles = pgTable("userBusinessRoles", { id: serial("id").primaryKey(), userId: integer("userId").notNull().unique(), role: businessRoleEnum("role").notNull().default("sales"), isActive: boolean("isActive").notNull().default(true), updatedAt: timestamp("updatedAt").defaultNow().notNull() });
export const customRoles = pgTable("customRoles", { id: serial("id").primaryKey(), name: varchar("name", { length: 80 }).notNull().unique(), description: varchar("description", { length: 320 }), permissionsJson: jsonb("permissionsJson").notNull(), isActive: boolean("isActive").notNull().default(true), createdBy: integer("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull() });
export const userCustomRoles = pgTable("userCustomRoles", { id: serial("id").primaryKey(), userId: integer("userId").notNull().unique(), customRoleId: integer("customRoleId").notNull(), isActive: boolean("isActive").notNull().default(true), updatedBy: integer("updatedBy").notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull() });
export const pendingAccessRequests = pgTable("pendingAccessRequests", { id: serial("id").primaryKey(), userId: integer("userId").notNull().unique(), status: accessRequestStatusEnum("status").notNull().default("pending"), requestedAt: timestamp("requestedAt").defaultNow().notNull(), reviewedAt: timestamp("reviewedAt"), reviewedBy: integer("reviewedBy"), note: varchar("note", { length: 500 }) });
export const staffAccessInvites = pgTable("staffAccessInvites", { id: serial("id").primaryKey(), name: varchar("name", { length: 160 }).notNull(), email: varchar("email", { length: 320 }).notNull().unique(), customRoleId: integer("customRoleId").notNull(), isActive: boolean("isActive").notNull().default(true), invitedBy: integer("invitedBy").notNull(), invitedAt: timestamp("invitedAt").defaultNow().notNull(), acceptedByUserId: integer("acceptedByUserId"), acceptedAt: timestamp("acceptedAt") });
export const shopSettings = pgTable("shopSettings", { id: serial("id").primaryKey(), shopName: varchar("shopName", { length: 160 }).notNull(), arabicShopName: varchar("arabicShopName", { length: 160 }), crNumber: varchar("crNumber", { length: 80 }), currency: varchar("currency", { length: 8 }).notNull().default("BHD"), phone: varchar("phone", { length: 50 }), email: varchar("email", { length: 320 }), address: text("address"), invoiceTerms: text("invoiceTerms"), invoicePrefix: varchar("invoicePrefix", { length: 16 }).notNull().default("INV"), vatEnabled: boolean("vatEnabled").notNull().default(false), vatRate: decimal("vatRate", { precision: 5, scale: 3 }).notNull().default("10.000"), vatNumber: varchar("vatNumber", { length: 80 }), updatedBy: integer("updatedBy"), updatedAt: timestamp("updatedAt").defaultNow().notNull() });
export const customers = pgTable("customers", { id: serial("id").primaryKey(), name: varchar("name", { length: 160 }).notNull(), phone: varchar("phone", { length: 50 }).notNull(), email: varchar("email", { length: 320 }), address: text("address"), notes: text("notes"), preferredContact: varchar("preferredContact", { length: 40 }), isActive: boolean("isActive").notNull().default(true), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull() });
export const measurementProfiles = pgTable("measurementProfiles", { id: serial("id").primaryKey(), customerId: integer("customerId").notNull(), version: integer("version").notNull(), measurementsJson: jsonb("measurementsJson").notNull(), fitPreference: varchar("fitPreference", { length: 100 }), collarStyle: varchar("collarStyle", { length: 100 }), pocketStyle: varchar("pocketStyle", { length: 100 }), notes: text("notes"), effectiveDate: date("effectiveDate", { mode: "date" }).notNull(), createdBy: integer("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const tailoringOrders = pgTable("tailoringOrders", { id: serial("id").primaryKey(), orderNumber: varchar("orderNumber", { length: 60 }).notNull().unique(), customerId: integer("customerId").notNull(), saleId: integer("saleId"), measurementProfileId: integer("measurementProfileId"), assignedTailorId: integer("assignedTailorId"), garmentType: varchar("garmentType", { length: 80 }).notNull().default("Thoub"), quantity: integer("quantity").notNull().default(1), status: tailoringOrderStatusEnum("status").notNull().default("draft"), dueDate: date("dueDate", { mode: "date" }), price: decimal("price", { precision: 12, scale: 3 }).notNull().default("0"), customerSuppliedFabric: boolean("customerSuppliedFabric").notNull().default(false), fabricNotes: text("fabricNotes"), notes: text("notes"), productionNotes: text("productionNotes"), createdBy: integer("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull() });
export const inventoryItems = pgTable("inventoryItems", { id: serial("id").primaryKey(), code: varchar("code", { length: 60 }).notNull().unique(), name: varchar("name", { length: 160 }).notNull(), inventoryType: inventoryItemTypeEnum("inventoryType").notNull().default("material"), category: inventoryCategoryEnum("category").notNull(), color: varchar("color", { length: 60 }), size: varchar("size", { length: 60 }), widthInches: decimal("widthInches", { precision: 10, scale: 2 }), unit: varchar("unit", { length: 40 }).notNull().default("Meters"), quantity: decimal("quantity", { precision: 12, scale: 3 }).notNull().default("0"), rollCount: integer("rollCount").notNull().default(0), metersPerRoll: decimal("metersPerRoll", { precision: 12, scale: 3 }), minThreshold: decimal("minThreshold", { precision: 12, scale: 3 }).notNull().default("0"), costPerUnit: decimal("costPerUnit", { precision: 12, scale: 3 }).notNull().default("0"), salePrice: decimal("salePrice", { precision: 12, scale: 3 }).notNull().default("0"), isActive: boolean("isActive").notNull().default(true), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull() });
export const stockMovements = pgTable("stockMovements", { id: serial("id").primaryKey(), inventoryItemId: integer("inventoryItemId").notNull(), movementType: stockMovementTypeEnum("movementType").notNull(), quantityChange: decimal("quantityChange", { precision: 12, scale: 3 }).notNull(), quantityBefore: decimal("quantityBefore", { precision: 12, scale: 3 }).notNull(), quantityAfter: decimal("quantityAfter", { precision: 12, scale: 3 }).notNull(), referenceType: varchar("referenceType", { length: 40 }), referenceId: integer("referenceId"), notes: text("notes"), createdBy: integer("createdBy"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const services = pgTable("services", { id: serial("id").primaryKey(), sku: varchar("sku", { length: 60 }).notNull().unique(), name: varchar("name", { length: 160 }).notNull(), category: serviceCategoryEnum("category").notNull(), description: text("description"), unitPrice: decimal("unitPrice", { precision: 12, scale: 3 }).notNull(), inventoryItemId: integer("inventoryItemId"), defaultFabricMeters: decimal("defaultFabricMeters", { precision: 12, scale: 3 }), isActive: boolean("isActive").notNull().default(true), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull() });
export const sales = pgTable("sales", { id: serial("id").primaryKey(), saleNumber: varchar("saleNumber", { length: 60 }).notNull().unique(), clientReference: varchar("clientReference", { length: 120 }).unique(), customerId: integer("customerId"), customerNameSnapshot: varchar("customerNameSnapshot", { length: 160 }).notNull(), customerPhoneSnapshot: varchar("customerPhoneSnapshot", { length: 50 }), subtotal: decimal("subtotal", { precision: 12, scale: 3 }).notNull(), discount: decimal("discount", { precision: 12, scale: 3 }).notNull().default("0"), vatRate: decimal("vatRate", { precision: 5, scale: 3 }).notNull().default("0"), vatAmount: decimal("vatAmount", { precision: 12, scale: 3 }).notNull().default("0"), total: decimal("total", { precision: 12, scale: 3 }).notNull(), paidAmount: decimal("paidAmount", { precision: 12, scale: 3 }).notNull().default("0"), paymentMethod: paymentMethodEnum("paymentMethod").notNull(), paymentStatus: paymentStatusEnum("paymentStatus").notNull().default("paid"), source: saleSourceEnum("source").notNull().default("counter"), sessionId: integer("sessionId"), discountCodeId: integer("discountCodeId"), discountCodeSnapshot: varchar("discountCodeSnapshot", { length: 80 }), returnOfSaleId: integer("returnOfSaleId"), returnMode: varchar("returnMode", { length: 20 }), returnReason: text("returnReason"), createdBy: integer("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const saleItems = pgTable("saleItems", { id: serial("id").primaryKey(), saleId: integer("saleId").notNull(), serviceId: integer("serviceId"), inventoryItemId: integer("inventoryItemId"), nameSnapshot: varchar("nameSnapshot", { length: 160 }).notNull(), quantity: decimal("quantity", { precision: 12, scale: 3 }).notNull(), unitPrice: decimal("unitPrice", { precision: 12, scale: 3 }).notNull(), lineDiscount: decimal("lineDiscount", { precision: 12, scale: 3 }).notNull().default("0"), lineTotal: decimal("total", { precision: 12, scale: 3 }).notNull(), assignedTailorId: integer("assignedTailorId"), measurementProfileId: integer("measurementProfileId") });
export const posSessions = pgTable("posSessions", { id: serial("id").primaryKey(), sessionNumber: varchar("sessionNumber", { length: 60 }).notNull().unique(), status: posSessionStatusEnum("status").notNull().default("open"), openedBy: integer("openedBy").notNull(), openingCash: decimal("openingCash", { precision: 12, scale: 3 }).notNull().default("0"), closingCash: decimal("closingCash", { precision: 12, scale: 3 }), openedAt: timestamp("openedAt").defaultNow().notNull(), closedAt: timestamp("closedAt"), notes: text("notes") });
export const posOrders = pgTable("posOrders", { id: serial("id").primaryKey(), orderNumber: varchar("orderNumber", { length: 60 }).notNull().unique(), sessionId: integer("sessionId"), customerId: integer("customerId"), status: posOrderStatusEnum("status").notNull().default("held"), cartJson: jsonb("cartJson").notNull(), note: text("note"), createdBy: integer("createdBy").notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), heldAt: timestamp("heldAt").defaultNow().notNull() });
export const posPayments = pgTable("posPayments", { id: serial("id").primaryKey(), saleId: integer("saleId").notNull(), method: paymentMethodEnum("method").notNull(), amount: decimal("amount", { precision: 12, scale: 3 }).notNull(), reference: varchar("reference", { length: 160 }), createdBy: integer("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const discountCodes = pgTable("discountCodes", { id: serial("id").primaryKey(), code: varchar("code", { length: 80 }).notNull().unique(), type: discountTypeEnum("type").notNull(), value: decimal("value", { precision: 12, scale: 3 }).notNull(), maxDiscount: decimal("maxDiscount", { precision: 12, scale: 3 }), minSubtotal: decimal("minSubtotal", { precision: 12, scale: 3 }).notNull().default("0"), usageLimit: integer("usageLimit"), usedCount: integer("usedCount").notNull().default(0), isActive: boolean("isActive").notNull().default(true), expiresAt: timestamp("expiresAt"), createdBy: integer("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const invoices = pgTable("invoices", { id: serial("id").primaryKey(), saleId: integer("saleId").notNull().unique(), invoiceNumber: varchar("invoiceNumber", { length: 60 }).notNull().unique(), status: invoiceStatusEnum("status").notNull(), issuedAt: timestamp("issuedAt").defaultNow().notNull(), dueDate: date("dueDate", { mode: "date" }), notes: text("notes") });
export const invoicePayments = pgTable("invoicePayments", { id: serial("id").primaryKey(), invoiceId: integer("invoiceId").notNull(), amount: decimal("amount", { precision: 12, scale: 3 }).notNull(), paymentMethod: paymentMethodEnum("paymentMethod").notNull(), reference: varchar("reference", { length: 160 }), previousPaidAmount: decimal("previousPaidAmount", { precision: 12, scale: 3 }).notNull().default("0"), paidTotal: decimal("paidTotal", { precision: 12, scale: 3 }).notNull(), remainingAmount: decimal("remainingAmount", { precision: 12, scale: 3 }).notNull(), createdBy: integer("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const invoiceDeliveries = pgTable("invoiceDeliveries", { id: serial("id").primaryKey(), invoiceId: integer("invoiceId").notNull(), channel: invoiceDeliveryChannelEnum("channel").notNull(), recipient: varchar("recipient", { length: 320 }), status: invoiceDeliveryStatusEnum("status").notNull().default("prepared"), message: text("message"), error: text("error"), createdBy: integer("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const customerBalanceDeliveries = pgTable("customerBalanceDeliveries", { id: serial("id").primaryKey(), customerId: integer("customerId").notNull(), channel: invoiceDeliveryChannelEnum("channel").notNull(), recipient: varchar("recipient", { length: 320 }), status: invoiceDeliveryStatusEnum("status").notNull().default("prepared"), message: text("message"), error: text("error"), createdBy: integer("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const staffProfiles = pgTable("staffProfiles", { id: serial("id").primaryKey(), userId: integer("userId"), name: varchar("name", { length: 160 }).notNull(), phone: varchar("phone", { length: 50 }), jobTitle: varchar("jobTitle", { length: 100 }).notNull(), baseSalary: decimal("baseSalary", { precision: 12, scale: 3 }).notNull(), commissionRate: decimal("commissionRate", { precision: 8, scale: 3 }).notNull().default("0"), isActive: boolean("isActive").notNull().default(true), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull() });
export const staffDocuments = pgTable("staffDocuments", { id: serial("id").primaryKey(), staffProfileId: integer("staffProfileId").notNull(), label: varchar("label", { length: 120 }).notNull(), fileName: varchar("fileName", { length: 255 }).notNull(), contentType: varchar("contentType", { length: 120 }).notNull(), storageKey: varchar("storageKey", { length: 500 }).notNull(), storageUrl: varchar("storageUrl", { length: 600 }).notNull(), uploadedBy: integer("uploadedBy").notNull(), uploadedAt: timestamp("uploadedAt").defaultNow().notNull() });
export const attendance = pgTable("attendance", { id: serial("id").primaryKey(), staffProfileId: integer("staffProfileId").notNull(), workDate: date("workDate", { mode: "date" }).notNull(), status: attendanceStatusEnum("status").notNull(), absenceReason: varchar("absenceReason", { length: 40 }), absenceDetails: text("absenceDetails"), absenceDocumentId: integer("absenceDocumentId"), absenceDeduction: decimal("absenceDeduction", { precision: 12, scale: 3 }).notNull().default("0"), notes: text("notes"), recordedBy: integer("recordedBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const performanceRecords = pgTable("performanceRecords", { id: serial("id").primaryKey(), staffProfileId: integer("staffProfileId").notNull(), workDate: date("workDate", { mode: "date" }).notNull(), metric: varchar("metric", { length: 120 }).notNull(), units: decimal("units", { precision: 12, scale: 3 }).notNull(), commissionEarned: decimal("commissionEarned", { precision: 12, scale: 3 }).notNull().default("0"), notes: text("notes"), recordedBy: integer("recordedBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const salaryPayouts = pgTable("salaryPayouts", { id: serial("id").primaryKey(), staffProfileId: integer("staffProfileId").notNull(), payPeriod: varchar("payPeriod", { length: 20 }).notNull(), payslipNumber: varchar("payslipNumber", { length: 60 }).unique(), baseSalary: decimal("baseSalary", { precision: 12, scale: 3 }).notNull(), allowances: decimal("allowances", { precision: 12, scale: 3 }).notNull().default("0"), overtime: decimal("overtime", { precision: 12, scale: 3 }).notNull().default("0"), performanceBonus: decimal("performanceBonus", { precision: 12, scale: 3 }).notNull().default("0"), deductions: decimal("deductions", { precision: 12, scale: 3 }).notNull().default("0"), deductionDetails: text("deductionDetails"), netSalary: decimal("netSalary", { precision: 12, scale: 3 }).notNull(), notes: text("notes"), approvedBy: integer("approvedBy").notNull(), paidAt: timestamp("paidAt").defaultNow().notNull() });
export const auditLogs = pgTable("auditLogs", { id: serial("id").primaryKey(), actorId: integer("actorId").notNull(), action: varchar("action", { length: 100 }).notNull(), entityType: varchar("entityType", { length: 80 }).notNull(), entityId: integer("entityId"), detailsJson: text("detailsJson"), createdAt: timestamp("createdAt").defaultNow().notNull() });


export const authSessions = pgTable("authSessions", {
  id: serial("id").primaryKey(),
  tokenHash: varchar("tokenHash", { length: 128 }).notNull().unique(),
  userId: integer("userId").notNull(),
  expiresAt: timestamp("expiresAt").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  lastUsedAt: timestamp("lastUsedAt").defaultNow().notNull(),
});

export const passwordResetTokens = pgTable("passwordResetTokens", {
  id: serial("id").primaryKey(),
  tokenHash: varchar("tokenHash", { length: 128 }).notNull().unique(),
  userId: integer("userId").notNull(),
  expiresAt: timestamp("expiresAt").notNull(),
  usedAt: timestamp("usedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
