import { useMemo, useState } from "react";
import { ClipboardCheck, Loader2, Scissors, Search, UserRoundCheck } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

const statuses = ["draft", "confirmed", "cutting", "stitching", "fitting", "ready", "handed_over", "cancelled"] as const;
const statusLabel = (status: string) => status.replaceAll("_", " ");
const date = (value: unknown) => value ? new Date(value as string).toLocaleDateString() : "No due date";
const money = (amount: unknown) => `BHD ${Number(amount || 0).toFixed(3)}`;

function Busy() { return <div className="flex min-h-[300px] items-center justify-center text-muted-foreground"><Loader2 className="mr-2 h-5 w-5 animate-spin" />Loading tailoring orders…</div>; }
function Heading() { return <div><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Bespoke production</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Tailoring orders</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Track tailoring work from confirmation through fitting and handover. New tailoring orders are created in Point of Sale.</p></div>; }
function Field({ name, label, type = "text", value, required, textarea, min, step }: { name: string; label: string; type?: string; value?: string; required?: boolean; textarea?: boolean; min?: string; step?: string }) { return <div className="space-y-1.5"><Label htmlFor={name}>{label}</Label>{textarea ? <Textarea id={name} name={name} defaultValue={value} /> : <Input id={name} name={name} type={type} min={min} step={step} required={required} defaultValue={value} />}</div>; }

export default function TailoringOrders() {
  const [selectedOrderId, setSelectedOrderId] = useState<number | null>(null); const [orderSearch, setOrderSearch] = useState("");
  const orderListInput = useMemo(() => ({ search: orderSearch || undefined }), [orderSearch]);
  const orders = trpc.erp.tailoring.list.useQuery(orderListInput);
  const staff = trpc.erp.staff.list.useQuery();
  const utils = trpc.useUtils();
  const refresh = () => { utils.erp.tailoring.list.invalidate(); };
  const update = trpc.erp.tailoring.update.useMutation({ onSuccess: () => { refresh(); setSelectedOrderId(null); toast.success("Production order updated"); }, onError: error => toast.error(error.message) });
  if (orders.isLoading || staff.isLoading) return <Busy />;
  if (orders.error || staff.error) return <p className="text-destructive">{orders.error?.message || staff.error?.message}</p>;
  const selectedOrder = orders.data?.find(order => order.id === selectedOrderId);
  return <div className="space-y-7"><Heading />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card><CardContent className="p-5"><ClipboardCheck className="h-5 w-5 text-primary" /><p className="mt-5 text-2xl font-semibold">{orders.data?.filter(order => !["handed_over", "cancelled"].includes(order.status)).length || 0}</p><p className="mt-1 text-sm font-medium">Open production orders</p><p className="mt-1 text-xs text-muted-foreground">Awaiting a production stage or handover.</p></CardContent></Card><Card><CardContent className="p-5"><Scissors className="h-5 w-5 text-primary" /><p className="mt-5 text-2xl font-semibold">{orders.data?.filter(order => ["cutting", "stitching", "fitting"].includes(order.status)).length || 0}</p><p className="mt-1 text-sm font-medium">In workshop</p><p className="mt-1 text-xs text-muted-foreground">Currently cutting, stitching, or fitting.</p></CardContent></Card><Card><CardContent className="p-5"><UserRoundCheck className="h-5 w-5 text-primary" /><p className="mt-5 text-2xl font-semibold">{orders.data?.filter(order => order.status === "ready").length || 0}</p><p className="mt-1 text-sm font-medium">Ready for handover</p><p className="mt-1 text-xs text-muted-foreground">Completed garments awaiting collection.</p></CardContent></Card><Card><CardContent className="p-5"><ClipboardCheck className="h-5 w-5 text-primary" /><p className="mt-5 text-2xl font-semibold">{orders.data?.filter(order => order.status === "handed_over").length || 0}</p><p className="mt-1 text-sm font-medium">Handed over</p><p className="mt-1 text-xs text-muted-foreground">Completed bespoke orders.</p></CardContent></Card></div>
    <Card><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle className="text-base">Production board</CardTitle><CardDescription>Every order keeps its client, measurement version, tailor, due date, and production notes together.</CardDescription></div><label className="relative w-full sm:max-w-sm"><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input value={orderSearch} onChange={event => setOrderSearch(event.target.value)} className="h-10 pl-9" placeholder="Search customer, order number, or date…" /></label></div></CardHeader><CardContent className="space-y-3">{orders.data?.length === 0 ? <div className="rounded-xl border border-dashed p-8 text-center"><p className="font-semibold">No tailoring orders in production</p><p className="mt-1 text-sm text-muted-foreground">Create the sale in Point of Sale, then return here to manage production and handover.</p></div> : orders.data?.map(order => <button type="button" key={order.id} onClick={() => setSelectedOrderId(order.id)} className="w-full rounded-xl border p-4 text-left transition hover:border-primary hover:bg-primary/[0.03]"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-primary">{order.orderNumber}</p><Badge variant={order.status === "handed_over" ? "secondary" : "outline"} className="capitalize">{statusLabel(order.status)}</Badge></div><p className="mt-2 font-medium">{order.garmentType} · {order.quantity} {order.quantity === 1 ? "piece" : "pieces"}</p><p className="mt-1 text-sm text-muted-foreground">{order.customerName}{order.customerPhone ? ` · ${order.customerPhone}` : ""}</p><p className="mt-2 text-xs text-muted-foreground">Measurement {order.measurementVersion ? `version ${order.measurementVersion}` : "not selected"} · {order.tailorName || "Tailor not assigned"}</p>{order.sale ? <p className="mt-2 text-xs font-medium text-primary">Sale {order.sale.saleNumber} · {money(order.sale.paidAmount)} paid of {money(order.sale.total)} · {statusLabel(order.sale.paymentStatus)}</p> : <p className="mt-2 text-xs text-amber-700">No linked sale recorded</p>}</div><div className="sm:text-right"><p className="font-semibold">{money(order.price)}</p><p className="mt-1 text-sm text-muted-foreground">Due {date(order.dueDate)}</p><p className="mt-3 text-xs font-medium text-primary">Open production details →</p></div></div></button>)}</CardContent></Card>
    <Dialog open={!!selectedOrder} onOpenChange={open => !open && setSelectedOrderId(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{selectedOrder?.orderNumber} · {selectedOrder?.garmentType}</DialogTitle><DialogDescription>Update the production stage, tailor, due date, and handover notes as the garment moves through the workshop.</DialogDescription></DialogHeader>{selectedOrder && <form className="space-y-4" onSubmit={event => { event.preventDefault(); const f = new FormData(event.currentTarget); update.mutate({ id: selectedOrder.id, assignedTailorId: f.get("assignedTailorId") ? Number(f.get("assignedTailorId")) : undefined, status: String(f.get("status")) as typeof statuses[number], dueDate: String(f.get("dueDate") || "") || undefined, productionNotes: String(f.get("productionNotes") || "") }); }}><div className="grid gap-3 rounded-xl bg-muted/50 p-4 sm:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Client</p><p className="mt-1 font-semibold">{selectedOrder.customerName}</p><p className="mt-1 text-sm text-muted-foreground">Measurement {selectedOrder.measurementVersion ? `version ${selectedOrder.measurementVersion}` : "not selected"}</p>{selectedOrder.sale ? <p className="mt-2 text-sm font-medium text-primary">Sale {selectedOrder.sale.saleNumber} · {money(selectedOrder.sale.paidAmount)} paid of {money(selectedOrder.sale.total)} · {statusLabel(selectedOrder.sale.paymentStatus)}{selectedOrder.invoice ? ` · Invoice ${selectedOrder.invoice.invoiceNumber}` : ""}</p> : <p className="mt-2 text-sm text-amber-700">This order has no linked sale record.</p>}</div><div><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Order notes</p><p className="mt-1 text-sm text-muted-foreground whitespace-pre-wrap">{selectedOrder.notes || "No order notes."}</p></div></div><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Production stage</Label><select name="status" defaultValue={selectedOrder.status} className="h-10 w-full rounded-md border bg-white px-3">{statuses.map(status => <option key={status} value={status}>{statusLabel(status)}</option>)}</select></div><div className="space-y-1.5"><Label>Assigned tailor</Label><select name="assignedTailorId" defaultValue={selectedOrder.assignedTailorId || ""} className="h-10 w-full rounded-md border bg-white px-3"><option value="">Unassigned</option>{staff.data?.map(member => <option key={member.id} value={member.id}>{member.name}</option>)}</select></div></div><Field name="dueDate" label="Due date" type="date" value={selectedOrder.dueDate ? new Date(selectedOrder.dueDate).toISOString().slice(0, 10) : ""} /><Field name="productionNotes" label="Production / fitting / handover notes" textarea value={selectedOrder.productionNotes || ""} /><Button className="w-full" disabled={update.isPending}>Save production update</Button></form>}</DialogContent></Dialog>
  </div>;
}
